### PR TITLE
Refactor of the code from assignment 1

### PR DESCRIPTION
**Pull request by mrtineide**
Refactored the code.
Extracted some large code blocks in the code into methods.
Removed also the test specific constructor to the robot class.

### CODE REVIEW

**Comment by mrtineide** [comment]
Hva synes dere?

**Comment by mrtineide** [comment]
I removed the need to have a test specific constructor in the robot by removing the filename argument from the constructor and moved into a set function. This removes the need to load the texture at initialization and therefore the test code of robot do not rely on a full game to be loaded. This makes the robot class easier to test with the test that are written.

**Comment by mrtineide** [comment]
This fixes #22

**Review by KimAndreG — APPROVED** [review]
Ser bra ut dette her!

**Review by TheLimeFreak — APPROVED** [review]
looks good

**Review by OdinBjerga — APPROVED** [review]
👍

**Pull request merged**
